### ISSUE TITLE
Can this code act as Master side

### ISSUE THREAD

**Issue by aifei7320** [vectorgrp/XCPlite#14]
As Title. the demo code is act as an slave, can this code read an A2L file, and read data from ecu?

**Comment by Z-ZWBY** [comment]
i think you should use Canape to read data from the demo

**Comment by aifei7320** [comment]
Thank you, i want to record only a few messages through xcp, i have read some protocol, it's not very difficult to achive that right?  A CTO command is enough?

**Comment by Z-ZWBY** [comment]
The code is designed for computer（linux and win platform）.if your code is running on the ecu, you should not use this code. You can download XCPbasic on the Vector web.i only use the Canape to read data and not try the CTO.
I only run the XCPLIte on the linux ,i want to use it to send message and calibrate on the ROS ,i  am trying it.

**Comment by aifei7320** [comment]
Thanks for your advice.
