### ISSUE TITLE
Bug in GET_DAQ_CLOCK_MULTICAST fixed

### ISSUE THREAD

**Issue by RainerZ** [vectorgrp/XCPlite#19]
Fixed the GET_DAQ_CLOCK_MULTICAST problem.
High dword and low dword of timestamp swapped. 
Wonder why CANape did not complain about this.
Measurement just started with some undeterministic delay.

**Comment by Z-ZWBY** [comment]
Hello @RainerZ 

I run the lastest V5 and there is still issue 'The determination of the XCP 1.3 DAQ start time failed' here, should i set the CANAPE, ? But i does not find the path in the CANAPE 17.
