### ISSUE TITLE
Segmentation Fault using local variables..

### ISSUE THREAD

**Issue by lkopi246** [vectorgrp/XCPlite#23]
Hi,

I tried using local variables for creating parameter in a2l and while running it gave segmentation fault. 
So I want to ask, can we use local variables for creating parameters, or only global variables are valid for using in create parameter. 

I am very new to this xcp stuff.  Any help will be appreciated.

**Comment by RainerZ** [comment]
Hello,

Sorry, XCPlite does not support automatic local variables yet.

Automatic variables are located on the stackframe of the current block and do not have a constant memory address. 
XCPlite only supports dynamic memory addressing for class instances.

Static variables with local scope can be handled by newer CANape versions.
But this is very unusual programing style.
