### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by aaroniza0** [vectorgrp/XCPlite#38]
Hello,

I'm a senior computer engineering student working on my senior design project at the moment, my project requires reading some hardware through ethernet and the hardware lists xcp on udp/ip as the communication protocol. 

My team has to use a raspberry pi, would this program achieve this and work on the pi? If so, how would I install it on my raspberry pi?

Also, would it be possible to use python to read the values being read from the hardware?

Thanks,

aaroniza0

**Comment by RainerZ** [comment]
Hi aaroniza0,

I recommend to use the branch V6_WorkInProgress.
It is the upcoming newer version to be released soon.
Will be easier for us to support and we are interested in feedback.

Regards
Rainer



From: aaroniza0 ***@***.***>
Sent: Wednesday, August 30, 2023 3:36 PM
To: vectorgrp/XCPlite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [vectorgrp/XCPlite] Help (Issue #38)


Hello,

I'm a senior computer engineering student working on my senior design project at the moment, my project requires reading some hardware through ethernet and the hardware lists xcp on udp/ip as the communication protocol.

My team has to use a raspberry pi, would this program achieve this and work on the pi? If so, how would I install it on my raspberry pi?

Also, would it be possible to use python to read the values being read from the hardware?

Thanks,

aaroniza0

**Comment by aaroniza0** [comment]
I’m looking at the c++ demo in the V6_WorkInProgress but having trouble figuring out how I would collect data collected by the xcp slave, any ideas to accomplish this? This project I’m working on just needs to pull data from an xcp slave so i don’t think it’s too complicated to do, I’ve just never done this before.
