### ISSUE TITLE
The functionality corresponding to XCP_ENABLE_SO has not been implemented 

### ISSUE THREAD

**Issue by liudongxjtu** [vectorgrp/XCPlite#40]
The functionality corresponding to XCP_ENABLE_SO has not been implemented in the code. Manually enabling XCP_ENABLE_SO will result in a compilation error.

@ xcplite/src/xcpAppl.c Line 296

**Comment by RainerZ** [comment]
Hello,

sorry, this option is not implemented in the demo. We left the code partially in the demo, to indicate, that this option exists.
As this is a more advanced topic, I suggest to contact us directly (via CANape support ticket).

Regards
RainerZ
