### ISSUE TITLE
XcpServerReceiveThread can't be terminated cleanly

### ISSUE THREAD

**Issue by truecarfield** [vectorgrp/XCPlite#54]
### How to reproduce it?

Init a XCP server on TCP a after terminating a XCP server on UDP using XcpEthServerShutdown() within the same process

### What false behavior do you observe?

XcpServerReceiveThread isn't really destroyed when XcpEthServerShutdown() called, so the XCP server doesn't really reinited with TCP

### What correct behavior do you expect?

XcpServerReceiveThread terminated cleanly when XcpEthServerShutdown() is called

**Comment by RainerZ** [comment]
Thanks
Please check the latest commit on master, problem should be solved

**Comment by truecarfield** [comment]
> Thanks Please check the latest commit on master, problem should be solved

Thanks for the update, plz take a look on [this PR](https://github.com/vectorgrp/XCPlite/pull/55)
